name: combined-workflows-dev # ワークフロー名を決定

# トリガーの設定
on:
    push: # プッシュ(マージ)が発生したときにトリガー
        branches:
            - feature/*
            - develop
    pull_request: # プルリクエストが発生したときにトリガー
        branches:
            - develop
        types:
            - opened

# 環境変数の設定
env:
    OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
    OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
    OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
    OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
    OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

# ジョブの設定
jobs:
    filter-files: # 変更されたファイルを判定
        name: Determine Changed Files
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
        runs-on: ubuntu-latest
        outputs: # 判定結果を格納
            frontend: ${{ steps.filter.outputs.frontend }} # フロントエンド変更時
            backend: ${{ steps.filter.outputs.backend }} # バックエンド変更時
        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: Determine changed files # 変更されたファイルを判定
              id: filter
              uses: dorny/paths-filter@v3
              with:
                  base: develop
                  filters: |
                      frontend:
                        - 'react/**/*.ts'
                        - 'react/**/*.tsx'
                      backend:
                        - 'fastapi/**/*.py'

    frontend-format-lint-test: # フロントエンドのフォーマット、静的解析、テストを実施
        name: Frontend Format & Lint & Test
        needs: filter-files
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') && needs.filter-files.outputs.frontend == 'true') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'frontend'))
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # フルクローンする

            - name: Set up Node.js # Node.js をセットアップ
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache-dependency-path: react/package-lock.json # react内のロックファイルをキャッシュ

            - name: Clear npm cache # npm キャッシュをクリア
              run: npm cache clean --force

            - name: Install dependencies # 依存関係をインストール
              run: |
                  cd react
                  npm install

            - name: Run Prettier check # Prettierでコードフォーマットをチェック
              run: |
                  cd react
                  npm run prettier -- --check .

            - name: Run ESLint # ESLintで静的解析を実施
              run: |
                  cd react
                  npm run lint -- .

            - name: Run tests # テストを実行
              run: |
                  cd react
                  npm run test

    backend-format-lint-test:
        name: Backend Format & Lint & Test
        needs: filter-files
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') && needs.filter-files.outputs.backend == 'true') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'backend'))
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # フルクローンする

            - name: Set up Python # Python をセットアップ
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"
                  cache: "pip"

            - name: Install dependencies # 依存関係をインストール
              run: |
                  cd fastapi
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Ruff Format # Ruffでコードフォーマットをチェック
              run: |
                  cd fastapi
                  ruff format --check .

            - name: Run Ruff Lint # Ruffで静的解析を実施
              run: |
                  cd fastapi
                  ruff check .

            - name: Run Mypy # Mypyで型チェックを実施
              run: |
                  cd fastapi
                  mypy .

            - name: Run pytest # pytestでテストを実行
              run: |
                  cd fastapi
                  pytest .

    sonar-analyze:
        name: Sonar Analyze
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v5.0.0
          with:
            args: >
                -Dsonar.projectKey=oimurat_combined-workflows
                -Dsonar.organization=systena-dx
          env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    frontend-build-and-push: # フロントエンドのビルドとプッシュを行うジョブ
        name: Frontend Build & Push
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: Get latest tag
              id: get_tag
              run: |
                git fetch --tags
                TAG=$(git describe --tags --abbrev=0 || echo "none")
                echo "Found tag: $TAG"
                echo "tag=$TAG" >> $GITHUB_OUTPUT

            - name: Docker build # Docker イメージをビルド
              if: startsWith(steps.get_tag.outputs.tag, 'dev-build-')
              run: docker build . --file react/Dockerfile --tag nrt.ocir.io/nrcmxxv7sjse/ec_service_test:nodejs-${{ github.sha }}

            - name: Login OCIR # OCIR にログイン
              if: startsWith(steps.get_tag.outputs.tag, 'dev-build-')
              uses: oracle-actions/login-ocir@v1.3.0
              with:
                auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

            - name: Push container image # コンテナイメージを OCIR にプッシュ
              if: startsWith(steps.get_tag.outputs.tag, 'dev-build-')
              run: docker push nrt.ocir.io/nrcmxxv7sjse/ec_service_test:nodejs-${{ github.sha }}

    backend-build-and-push: # バックエンドのビルドとプッシュを行うジョブ
        name: Backend Build & Push
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: Get latest tag
              id: get_tag
              run: |
                git fetch --tags
                TAG=$(git describe --tags --abbrev=0 || echo "none")
                echo "Found tag: $TAG"
                echo "tag=$TAG" >> $GITHUB_OUTPUT

            - name: Docker build # Docker イメージをビルド
              if: startsWith(steps.get_tag.outputs.tag, 'dev-build-')
              run: docker build . --file fastapi/Dockerfile --tag nrt.ocir.io/nrcmxxv7sjse/ec_service_test:python-${{ github.sha }}

            - name: Login OCIR # OCIR にログイン
              if: startsWith(steps.get_tag.outputs.tag, 'dev-build-')
              uses: oracle-actions/login-ocir@v1.3.0
              with:
                auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

            - name: Push container image # コンテナイメージを OCIR にプッシュ
              if: startsWith(steps.get_tag.outputs.tag, 'dev-build-')
              run: docker push nrt.ocir.io/nrcmxxv7sjse/ec_service_test:python-${{ github.sha }}